"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { CalendarDays, Check, ChevronRight, ClipboardCheck, LoaderCircle, Plus, Search, X } from "lucide-react";
import { AdminControlPortal, AdminDatePicker, AdminDropdown, AdminFilterControlStyles, SMDurcharbeitFilterTheme } from "@/components/admin/AdminFilterControls";
import { requestSMDurcharbeitCampaign } from "@/lib/api/backend";
import { subscribeToAuthSessionChanges } from "@/lib/auth/sessionRegistry";
import type { SMDurcharbeitCampaign, SMDurcharbeitCampaignDraft, SMDurcharbeitCampaignOptions, SMDurcharbeitMonthlySummary, SMDurcharbeitPublicationPreview, SMDurcharbeitTarget } from "@/types/smSMDurcharbeitCampaign";
import { SMDurcharbeitMonthlyReport } from "./SMDurcharbeitMonthlyReport";
import { SMDurcharbeitCampaignHistory } from "./SMDurcharbeitCampaignHistory";

const primary = "flex h-9 items-center justify-center gap-1.5 rounded-lg bg-gradient-to-b from-blue-600 to-blue-700 px-3 text-[11px] font-semibold text-white shadow-[inset_0_1px_0_rgba(255,255,255,.3),0_0_0_1px_#1d4ed8,0_2px_6px_rgba(37,99,235,.14)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:bg-none disabled:bg-gray-100 disabled:text-gray-600 disabled:shadow-none";
const secondary = "flex h-9 items-center justify-center gap-1.5 rounded-lg border border-black/[.08] bg-gradient-to-b from-white to-gray-50 px-3 text-[11px] font-semibold text-gray-600 shadow-[0_1px_3px_rgba(0,0,0,.03)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:opacity-45";
const field = "h-10 w-full rounded-lg border border-black/[.08] bg-white px-3 text-[12px] text-gray-800 outline-none focus:border-blue-400";
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Vienna", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function monthName(month: string) { return new Intl.DateTimeFormat("de-AT", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${month}T12:00:00Z`)); }
function campaignMonths(campaign: SMDurcharbeitCampaign) {
  const result: string[] = [];
  for (let date = new Date(`${campaign.startDate.slice(0, 7)}-01T12:00:00Z`); date.toISOString().slice(0, 7) <= campaign.endDate.slice(0, 7) && result.length < 24; date.setUTCMonth(date.getUTCMonth() + 1)) result.push(date.toISOString().slice(0, 10));
  return result;
}
function emptyDraft(): SMDurcharbeitCampaignDraft {
  const startDate = today(), end = new Date(`${startDate}T12:00:00Z`); end.setUTCMonth(Math.floor(end.getUTCMonth() / 3) * 3 + 3, 0);
  return { name: "", startDate, endDate: end.toISOString().slice(0, 10), questionnaireVersionId: "", rosterDraft: [] };
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <div><p className="mb-1.5 text-[10px] font-semibold text-gray-500">{label}</p>{children}</div>; }
function CampaignDialog({ title, children, onClose, error }: { title: string; children: ReactNode; onClose: () => void; error: string | null }) {
  const ref = useRef<HTMLDialogElement>(null);
  const [portalContainer, setPortalContainer] = useState<HTMLElement | null>(null);
  useEffect(() => { const dialog = ref.current; setPortalContainer(dialog); dialog?.showModal(); return () => { dialog?.close(); }; }, []);
  return <dialog ref={ref} onCancel={event => { event.preventDefault(); onClose(); }} className="m-auto w-[min(520px,calc(100vw-32px))] rounded-2xl border border-black/[.06] bg-white p-5 shadow-2xl backdrop:bg-slate-950/20 backdrop:backdrop-blur-sm">
    <header className="mb-4 flex items-center justify-between gap-3"><h2 className="text-[15px] font-semibold text-gray-900">{title}</h2><button type="button" onClick={onClose} aria-label="Dialog schließen" className="flex h-7 w-7 items-center justify-center rounded-lg bg-gray-50 text-gray-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"><X size={14} /></button></header>{error ? <p role="alert" className="mb-4 text-[11px] leading-relaxed text-red-700">{error}</p> : null}<AdminControlPortal container={portalContainer}>{children}</AdminControlPortal>
  </dialog>;
}

export function SmSMDurcharbeitCampaignWorkspace() {
  const [campaigns, setCampaigns] = useState<SMDurcharbeitCampaign[]>([]), [options, setOptions] = useState<SMDurcharbeitCampaignOptions | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null), [month, setMonth] = useState(() => `${today().slice(0, 7)}-01`);
  const [draft, setDraft] = useState<SMDurcharbeitCampaignDraft | null>(null), [query, setQuery] = useState("");
  const [result, setResult] = useState<{ targets: SMDurcharbeitTarget[]; summary: SMDurcharbeitMonthlySummary } | null>(null);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState(0), [preview, setPreview] = useState<SMDurcharbeitPublicationPreview | null>(null), [confirmOverlap, setConfirmOverlap] = useState(false);
  const [editTarget, setEditTarget] = useState<SMDurcharbeitTarget | null>(null), [editOwner, setEditOwner] = useState(""), [editEligibility, setEditEligibility] = useState<"required" | "waived">("required"), [editScope, setEditScope] = useState("month");
  const [reason, setReason] = useState(""), [extend, setExtend] = useState(false), [endDate, setEndDate] = useState(""), [reactivate, setReactivate] = useState(false);
  const [marketDisplay, setMarketDisplay] = useState({ key: "", count: 100 });
  const [targetDisplay, setTargetDisplay] = useState({ key: "", count: 100 });
  const [cancelTarget, setCancelTarget] = useState<SMDurcharbeitTarget | null>(null);
  const [stateAction, setStateAction] = useState<SMDurcharbeitCampaign["status"] | null>(null);
  const [periodEdit, setPeriodEdit] = useState(false), [futureVersion, setFutureVersion] = useState("");
  const pending = useRef(false), selected = campaigns.find(campaign => campaign.id === selectedId) ?? null;
  const reload = useCallback(() => setReloadKey(key => key + 1), []);
  useEffect(() => subscribeToAuthSessionChanges(() => { setCampaigns([]); setOptions(null); setResult(null); setDraft(null); setSelectedId(null); setPreview(null); reload(); }), [reload]);
  useEffect(() => {
    let current = true; setLoading(true);
    Promise.all([requestSMDurcharbeitCampaign<{ campaigns: SMDurcharbeitCampaign[] }>(""), requestSMDurcharbeitCampaign<SMDurcharbeitCampaignOptions>("/options")])
      .then(([list, options]) => { if (!current) return; setCampaigns(list.campaigns); setOptions(options); setError(null); setSelectedId(id => id && list.campaigns.some(campaign => campaign.id === id) ? id : list.campaigns.find(campaign => campaign.status === "published")?.id ?? list.campaigns[0]?.id ?? null); })
      .catch(error => { if (current) setError(error instanceof Error ? error.message : "Kampagnen konnten nicht geladen werden."); })
      .finally(() => { if (current) setLoading(false); });
    return () => { current = false; };
  }, [reloadKey]);
  useEffect(() => {
    if (!selected || selected.status === "draft") { setResult(null); return; }
    let current = true; setResult(null);
    requestSMDurcharbeitCampaign<{ targets: SMDurcharbeitTarget[]; summary: SMDurcharbeitMonthlySummary }>(`/${selected.id}/targets?month=${encodeURIComponent(month)}`)
      .then(result => { if (current) setResult(result); }).catch(error => { if (current) setError(error instanceof Error ? error.message : "Monatsziele konnten nicht geladen werden."); });
    return () => { current = false; };
  }, [selected, month, reloadKey]);
  const act = async (action: () => Promise<void>) => {
    if (pending.current) return; pending.current = true; setBusy(true); setError(null);
    try { await action(); } catch (error) { setError(error instanceof Error ? error.message : "Die Änderung konnte nicht gespeichert werden."); }
    finally { pending.current = false; setBusy(false); }
  };
  const choose = (campaign: SMDurcharbeitCampaign) => {
    setSelectedId(campaign.id); setDraft(campaign.status === "draft" ? { name: campaign.name, startDate: campaign.startDate, endDate: campaign.endDate, questionnaireVersionId: campaign.questionnaireVersionId, rosterDraft: campaign.rosterDraft } : null);
    const months = campaignMonths(campaign), currentMonth = `${today().slice(0, 7)}-01`; setMonth(months.includes(currentMonth) ? currentMonth : months[0] ?? currentMonth); setError(null);
  };
  const rosterByMarket = useMemo(() => new Map(draft?.rosterDraft.map(row => [row.smMarketId, row]) ?? []), [draft?.rosterDraft]);
  const visibleMarkets = useMemo(() => (options?.markets ?? []).filter(market => `${market.name} ${market.address} ${market.city} ${market.sourcePerson ?? ""}`.toLocaleLowerCase("de-AT").includes(query.trim().toLocaleLowerCase("de-AT"))), [options?.markets, query]);
  const marketDisplayKey = `${selectedId ?? "new"}:${query}`;
  const marketDisplayCount = marketDisplay.key === marketDisplayKey ? marketDisplay.count : 100;
  const targetDisplayKey = `${selectedId}:${month}`;
  const targetDisplayCount = targetDisplay.key === targetDisplayKey ? targetDisplay.count : 100;
  const updateRoster = (marketId: string, smUserId?: string | null, checked = true) => {
    if (!draft) return;
    const next = new Map(draft.rosterDraft.map(row => [row.smMarketId, row]));
    if (!checked) next.delete(marketId); else next.set(marketId, { smMarketId: marketId, smUserId: smUserId === undefined ? options?.markets.find(market => market.id === marketId)?.assignedSmUserId ?? null : smUserId });
    setDraft({ ...draft, rosterDraft: [...next.values()] });
  };
  const saveDraft = async () => {
    if (!draft) return;
    await act(async () => {
      const response = await requestSMDurcharbeitCampaign<{ campaign: SMDurcharbeitCampaign }>(selected?.status === "draft" ? `/${selected.id}` : "", { ...draft, ...(selected?.status === "draft" ? { expectedRevision: selected.revision } : {}) }, selected?.status === "draft" ? "PATCH" : "POST");
      setSelectedId(response.campaign.id); setDraft(null); reload();
    });
  };
  const showPreview = () => { if (selected) void act(async () => { setPreview(await requestSMDurcharbeitCampaign<SMDurcharbeitPublicationPreview>(`/${selected.id}/preview`)); setConfirmOverlap(false); }); };
  const people = options?.people.map(person => ({ value: person.id, label: `${person.firstName} ${person.lastName}`.trim() })) ?? [];
  const questionnaires = options?.questionnaires.map(questionnaire => ({ value: questionnaire.id, label: questionnaire.name, description: `Version ${questionnaire.versionNumber}` })) ?? [];
  return <SMDurcharbeitFilterTheme enabled><AdminFilterControlStyles /><main className="min-h-full bg-[#f5f5f7] p-5 lg:p-7">
    <header className="mb-5 flex flex-wrap items-center justify-end gap-2"><Link href="/admin/sm/durcharbeit-verplanung/alt" className={secondary}>Datierte Einsätze</Link><button type="button" disabled={busy} onClick={() => { setSelectedId(null); setDraft(emptyDraft()); setResult(null); setError(null); }} className={primary}><Plus size={13} />Kampagne erstellen</button></header>
    {error ? <div className="mb-4 flex items-center justify-between gap-3 rounded-xl border border-red-100 bg-white px-4 py-3"><p role="alert" className="text-[11px] leading-relaxed text-red-700">{error}</p><button type="button" disabled={busy} onClick={reload} className={secondary}>Neu laden</button></div> : null}
    <div className="grid items-start gap-4 lg:grid-cols-[260px_minmax(0,1fr)]">
      <aside aria-label="Durcharbeit-Kampagnen" className="overflow-hidden rounded-2xl bg-white shadow-[0_2px_8px_rgba(0,0,0,.025)]"><h2 className="border-b border-black/[.05] px-4 py-3 text-[11px] font-semibold text-gray-600">Kampagnen</h2>
        {loading && !campaigns.length ? <div className="space-y-5 p-4 motion-safe:animate-pulse">{[0, 1, 2].map(i => <div key={i} className="h-8 rounded-lg bg-gray-50" />)}</div> : !campaigns.length ? <p className="p-4 text-[11px] leading-relaxed text-gray-600">Noch keine monatlichen Kampagnen. Bestehende datierte Einsätze bleiben über den Verlauf erreichbar.</p> : <ul>{campaigns.map(campaign => <li key={campaign.id}><button type="button" disabled={busy} aria-pressed={selectedId === campaign.id} onClick={() => choose(campaign)} className={`flex w-full items-center justify-between gap-2 border-b border-black/[.04] px-4 py-3 text-left last:border-0 ${selectedId === campaign.id ? "bg-blue-50/60" : "hover:bg-gray-50"}`}><span className="min-w-0"><span className="block truncate text-[12px] font-semibold text-gray-800">{campaign.name}</span><span className="mt-1 block text-[10px] text-gray-600">{campaign.status === "draft" ? "Entwurf" : campaign.status === "paused" ? "Pausiert" : campaign.status === "archived" ? "Archiviert" : today() > campaign.endDate ? "Beendet" : today() < campaign.startDate ? "Geplant" : "Laufend"} · {campaign.startDate.slice(0, 7)} – {campaign.endDate.slice(0, 7)}</span></span><ChevronRight size={12} className="shrink-0 text-gray-300" /></button></li>)}</ul>}
      </aside>
      <section className="min-w-0 space-y-4">
        {draft ? <div className="rounded-2xl bg-white p-5 shadow-[0_2px_8px_rgba(0,0,0,.025)]"><h2 className="mb-5 flex items-center gap-2 text-[15px] font-semibold text-gray-900"><ClipboardCheck size={16} className="text-blue-600" />Kampagnenentwurf</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><input aria-label="Kampagnenname" value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} className={field} /></Field><Field label="Fragebogen"><AdminDropdown value={draft.questionnaireVersionId} options={questionnaires} onChange={questionnaireVersionId => setDraft({ ...draft, questionnaireVersionId })} ariaLabel="Durcharbeit-Fragebogen" placeholder="Fragebogen wählen" searchable disabled={busy} /></Field><Field label="Beginn"><AdminDatePicker value={draft.startDate} onChange={startDate => setDraft({ ...draft, startDate })} ariaLabel="Kampagnenbeginn" /></Field><Field label="Ende"><AdminDatePicker value={draft.endDate} minDate={draft.startDate} onChange={endDate => setDraft({ ...draft, endDate })} ariaLabel="Kampagnenende" /></Field></div>
          <div className="mt-5 flex flex-wrap items-center justify-between gap-2 border-t border-black/[.05] pt-4"><h3 className="text-[12px] font-semibold text-gray-700">Märkte und Zuordnung <span className="ml-1 text-gray-600">{draft.rosterDraft.length}</span></h3><button type="button" disabled={busy || !options} onClick={() => setDraft({ ...draft, rosterDraft: options!.markets.map(market => rosterByMarket.get(market.id) ?? { smMarketId: market.id, smUserId: market.assignedSmUserId }) })} className={secondary}>Alle Märkte auswählen</button></div>
          <label className="mt-3 flex h-9 items-center gap-2 rounded-lg border border-black/[.06] px-3"><Search size={12} className="text-gray-600" /><input aria-label="Durcharbeit-Märkte suchen" value={query} onChange={event => setQuery(event.target.value)} placeholder="Markt, Adresse oder Verplanung suchen" className="min-w-0 flex-1 bg-transparent text-[11px] outline-none" /></label>
          <div className="mt-3 max-h-[430px] overflow-y-auto rounded-xl border border-black/[.05]">{visibleMarkets.slice(0, marketDisplayCount).map(market => { const row = rosterByMarket.get(market.id); return <div key={market.id} className="flex flex-wrap items-center gap-3 border-b border-black/[.04] px-3 py-2.5 last:border-0"><input type="checkbox" aria-label={`${market.name} auswählen`} checked={Boolean(row)} disabled={busy} onChange={event => updateRoster(market.id, undefined, event.target.checked)} className="accent-blue-600" /><div className="min-w-[180px] flex-1"><p className="text-[11px] font-semibold text-gray-700">{market.name}</p><p className="mt-0.5 text-[10px] text-gray-600">{market.address} · {market.postalCode} {market.city}</p>{market.sourcePerson ? <p className="mt-0.5 text-[10px] text-gray-600">Verplanung: {market.sourcePerson}</p> : null}</div><div className="w-[210px]"><AdminDropdown value={row?.smUserId ?? ""} options={people} onChange={person => updateRoster(market.id, person)} ariaLabel={`SM für ${market.name}`} placeholder="SM zuweisen" searchable disabled={busy || !row} /></div></div>; })}{!visibleMarkets.length ? <p className="p-4 text-[11px] text-gray-600">Keine passenden Durcharbeit-Märkte.</p> : null}</div>
          {visibleMarkets.length > marketDisplayCount ? <button type="button" className={`${secondary} mt-3`} onClick={() => setMarketDisplay({ key: marketDisplayKey, count: marketDisplayCount + 100 })}>Weitere Märkte · {marketDisplayCount}/{visibleMarkets.length}</button> : null}
          <footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setDraft(null)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || !draft.name.trim() || !draft.questionnaireVersionId} onClick={() => void saveDraft()} className={primary}>{busy ? <LoaderCircle size={12} className="motion-safe:animate-spin" /> : <Check size={12} />}Entwurf speichern</button></footer>
        </div> : selected ? <>
          <div className="rounded-2xl bg-white p-5 shadow-[0_2px_8px_rgba(0,0,0,.025)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[18px] font-semibold text-gray-900">{selected.name}</h2><p className="mt-1 flex items-center gap-1 text-[10px] text-gray-600"><CalendarDays size={11} />{selected.startDate} – {selected.endDate}</p></div><div className="flex flex-wrap gap-2">{selected.status === "draft" ? <><button type="button" onClick={() => choose(selected)} className={secondary}>Bearbeiten</button><button type="button" disabled={busy} onClick={showPreview} className={primary}>Vorschau &amp; Veröffentlichen</button></> : selected.status !== "archived" ? <><button type="button" disabled={busy} onClick={() => { setExtend(true); setEndDate(selected.endDate); setReason(""); setReactivate(false); }} className={secondary}>Verlängern</button><button type="button" disabled={busy} onClick={() => { setStateAction(selected.status === "paused" ? "published" : "paused"); setReason(""); }} className={secondary}>{selected.status === "paused" ? "Fortsetzen" : "Pausieren"}</button><button type="button" disabled={busy} onClick={() => { setStateAction("archived"); setReason(""); }} className={secondary}>Archivieren</button></> : null}</div></div>
            {selected.status === "draft" ? <p className="mt-5 text-[11px] text-gray-600">Der Entwurf ist für SMs noch nicht sichtbar. Vor der Veröffentlichung werden Zuordnungen und Überschneidungen geprüft.</p> : <div className="mt-5 grid gap-3 sm:grid-cols-[220px_1fr]"><AdminDropdown value={month} options={campaignMonths(selected).map(value => ({ value, label: monthName(value) }))} onChange={setMonth} ariaLabel="Kampagnenmonat" placeholder="Monat auswählen" /><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-[11px] text-gray-500">{result ? <><span><strong className="text-gray-900">{result.summary.completed}/{result.summary.required}</strong> erledigt</span><span>{result.summary.waived} ausgenommen</span><span>{result.summary.physicalVisits} tatsächliche Besuche</span></> : <span className="h-3 w-48 rounded bg-gray-100 motion-safe:animate-pulse" />}</div></div>}
          </div>
          {selected.status !== "draft" ? <div className="overflow-hidden rounded-2xl bg-white shadow-[0_2px_8px_rgba(0,0,0,.025)]"><header className="flex items-center justify-between gap-2 border-b border-black/[.05] px-4 py-3"><h3 className="text-[12px] font-semibold text-gray-700">Monatsziele</h3>{month > `${today().slice(0, 7)}-01` && selected.status !== "archived" ? <button type="button" disabled={busy} onClick={() => { setPeriodEdit(true); setFutureVersion(""); setReason(""); }} className={secondary}>Fragebogen für diesen Monat</button> : null}</header>{!result ? <div className="space-y-4 p-4 motion-safe:animate-pulse">{[0, 1, 2].map(id => <div key={id} className="h-9 rounded bg-gray-50" />)}</div> : <div className="overflow-x-auto"><table className="w-full text-left text-[11px]"><thead className="border-b border-black/[.04] text-[10px] uppercase tracking-wider text-gray-600"><tr><th className="px-4 py-3">Markt</th><th className="px-3 py-3">SM</th><th className="px-3 py-3">Monatsstand</th><th className="px-3 py-3">Besuche</th><th className="px-4 py-3"><span className="sr-only">Aktionen</span></th></tr></thead><tbody>{result.targets.slice(0, targetDisplayCount).map(target => <tr key={target.id} className="border-b border-black/[.035] last:border-0"><td className="px-4 py-3"><p className="font-semibold text-gray-700">{target.market.name}</p><p className="mt-0.5 text-[10px] text-gray-600">{target.market.address} · {target.market.city}</p></td><td className="px-3 py-3 text-gray-500">{target.smName}</td><td className="px-3 py-3 text-gray-500">{target.eligibility === "waived" ? "Ausgenommen" : target.completed ? "Erledigt" : target.draftVisitId ? "In Arbeit" : "Offen"}</td><td className="px-3 py-3 tabular-nums text-gray-500">{target.visitCount}</td><td className="px-4 py-3"><div className="flex justify-end gap-2">{target.latestSubmissionId ? <Link href={`/admin/sm/fbmanagement?submissionId=${encodeURIComponent(target.latestSubmissionId)}`} className={secondary}>Antworten</Link> : null}{target.draftVisitId ? <button type="button" disabled={busy} onClick={() => { setCancelTarget(target); setReason(""); }} className={secondary}>Entwurf verwerfen</button> : null}{selected.status !== "archived" && target.month >= `${today().slice(0, 7)}-01` ? <button type="button" disabled={busy} onClick={() => { setEditTarget(target); setEditOwner(target.smUserId); setEditEligibility(target.eligibility); setEditScope("month"); setReason(""); }} className={secondary}>Zuordnung</button> : null}</div></td></tr>)}</tbody></table>{result.targets.length > targetDisplayCount ? <div className="p-4"><button type="button" className={secondary} onClick={() => setTargetDisplay({ key: targetDisplayKey, count: targetDisplayCount + 100 })}>Weitere Monatsziele · {targetDisplayCount}/{result.targets.length}</button></div> : null}{!result.targets.length ? <p className="p-5 text-[11px] text-gray-600">Keine Monatsziele in diesem Zeitraum.</p> : null}</div>}</div> : null}
          {selected.status !== "draft" && result ? <SMDurcharbeitMonthlyReport campaign={selected} month={month} targets={result.targets} reloadKey={reloadKey} /> : null}
          <SMDurcharbeitCampaignHistory campaignId={selected.id} revision={selected.revision + reloadKey} />
        </> : !draft && !loading ? <div className="rounded-2xl bg-white p-8 text-center text-[12px] text-gray-600">Kampagne auswählen oder einen neuen Entwurf erstellen.</div> : null}
      </section>
    </div>
    {preview ? <CampaignDialog error={error} title="Kampagne veröffentlichen" onClose={() => { if (!busy) setPreview(null); }}><p className="text-[12px] font-semibold text-gray-800">{preview.campaign.name}</p><p className="mt-2 text-[11px] leading-relaxed text-gray-500">{preview.marketCount} Märkte · {preview.months.map(monthName).join(", ")} · {preview.targetCount} Monatsziele</p>{preview.unresolved.length ? <p className="mt-4 text-[11px] text-red-700">{preview.unresolved.length} Märkten fehlt ein aktiver SM. Bitte die Zuordnung im Entwurf ergänzen.</p> : null}{preview.overlapping.length || preview.legacy.length ? <label className="mt-4 flex items-start gap-2 text-[11px] leading-relaxed text-gray-600"><input type="checkbox" checked={confirmOverlap} onChange={event => setConfirmOverlap(event.target.checked)} className="mt-0.5 accent-blue-600" />{preview.overlapping.length} Überschneidungen mit Kampagnen und {preview.legacy.length} offenen datierten Einsätzen. Ich bestätige, dass dies separate Verpflichtungen sind.</label> : null}<p className="mt-4 text-[10px] leading-relaxed text-gray-600">Nach der Veröffentlichung sehen zugewiesene SMs ihre Märkte. Die Kampagne erzeugt keine geplanten Besuchstage oder Sollzeiten.</p><footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setPreview(null)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || Boolean(preview.unresolved.length) || Boolean((preview.overlapping.length || preview.legacy.length) && !confirmOverlap)} onClick={() => void act(async () => { await requestSMDurcharbeitCampaign(`/${preview.campaign.id}/publish`, { expectedRevision: preview.campaign.revision, previewToken: preview.previewToken, confirmOverlap }, "POST"); setPreview(null); reload(); })} className={primary}>Veröffentlichen</button></footer></CampaignDialog> : null}
    {editTarget ? <CampaignDialog error={error} title="Monatszuordnung bearbeiten" onClose={() => { if (!busy) setEditTarget(null); }}><p className="mb-4 text-[11px] text-gray-500">{editTarget.market.name} · {monthName(editTarget.month)}</p><div className="space-y-4"><Field label="Shelf Merchandiser"><AdminDropdown value={editOwner} options={people} onChange={setEditOwner} ariaLabel="Neuer SM" placeholder="SM wählen" searchable /></Field><Field label="Verpflichtung"><AdminDropdown value={editEligibility} options={[{ value: "required", label: "Besuch erforderlich" }, { value: "waived", label: "Markt ausnehmen" }]} onChange={value => setEditEligibility(value as "required" | "waived")} ariaLabel="Monatsverpflichtung" placeholder="Status" /></Field><Field label="Zeitraum"><AdminDropdown value={editScope} options={[{ value: "month", label: "Nur dieser Kalendermonat" }, { value: "future", label: "Ab diesem Kalendermonat" }]} onChange={setEditScope} ariaLabel="Änderungszeitraum" placeholder="Zeitraum" /></Field><Field label="Begründung"><input aria-label="Grund der Zuordnungsänderung" value={reason} onChange={event => setReason(event.target.value)} className={field} /></Field></div><p className="mt-4 text-[10px] leading-relaxed text-gray-600">Laufende Entwürfe sind geschützt. Frühere Besuche behalten ihren ursprünglichen SM und ihre Antworten.</p><footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setEditTarget(null)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || reason.trim().length < 3 || !editOwner} onClick={() => void act(async () => { await requestSMDurcharbeitCampaign(`/targets/${editTarget.id}`, { expectedRevision: editTarget.revision, smUserId: editOwner, eligibility: editEligibility, scope: editScope, reason }, "PATCH"); setEditTarget(null); reload(); })} className={primary}>Speichern</button></footer></CampaignDialog> : null}
    {cancelTarget?.draftVisitId ? <CampaignDialog error={error} title="Laufenden Entwurf verwerfen" onClose={() => { if (!busy) setCancelTarget(null); }}><p className="mb-4 text-[11px] leading-relaxed text-gray-500">{cancelTarget.market.name} · {monthName(cancelTarget.month)} · {cancelTarget.smName}</p><Field label="Begründung"><input value={reason} aria-label="Grund für das Verwerfen" onChange={event => setReason(event.target.value)} className={field} /></Field><p className="mt-4 text-[11px] leading-relaxed text-gray-500">Die noch nicht abgeschlossenen Antworten dieses Besuchs werden verworfen. Bereits abgeschlossene Besuche, ihr Monatsstand, Fotos und Zeiten bleiben erhalten. Dieser Schritt wird im Verlauf protokolliert.</p><footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setCancelTarget(null)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || reason.trim().length < 3} onClick={() => void act(async () => { await requestSMDurcharbeitCampaign(`/targets/${cancelTarget.id}/cancel-draft`, { expectedRevision: cancelTarget.revision, visitId: cancelTarget.draftVisitId, reason, confirmation: "CANCEL_SMDURCHARBEIT_DRAFT" }, "POST"); setCancelTarget(null); reload(); })} className={primary}>Entwurf verwerfen</button></footer></CampaignDialog> : null}
    {extend && selected ? <CampaignDialog error={error} title="Kampagne verlängern" onClose={() => { if (!busy) setExtend(false); }}><div className="space-y-4"><Field label="Neues Enddatum"><AdminDatePicker value={endDate} minDate={selected.endDate} onChange={setEndDate} ariaLabel="Neues Kampagnenende" /></Field><Field label="Begründung"><input aria-label="Grund der Verlängerung" value={reason} onChange={event => setReason(event.target.value)} className={field} /></Field>{selected.status === "paused" ? <label className="flex items-center gap-2 text-[11px] text-gray-600"><input type="checkbox" checked={reactivate} onChange={event => setReactivate(event.target.checked)} className="accent-blue-600" />Kampagne wieder freigeben</label> : null}</div><p className="mt-4 text-[10px] text-gray-600">Bestehende Monate bleiben erhalten. Zusätzliche Monate beginnen mit leeren Antworten und der zuletzt gültigen Zuordnung.</p><footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setExtend(false)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || reason.trim().length < 3 || endDate <= selected.endDate} onClick={() => void act(async () => { await requestSMDurcharbeitCampaign(`/${selected.id}/extend`, { expectedRevision: selected.revision, endDate, reason, reactivate }, "POST"); setExtend(false); reload(); })} className={primary}>Verlängern</button></footer></CampaignDialog> : null}
    {stateAction && selected ? <CampaignDialog error={error} title={stateAction === "archived" ? "Kampagne archivieren" : stateAction === "paused" ? "Kampagne pausieren" : "Kampagne fortsetzen"} onClose={() => { if (!busy) setStateAction(null); }}><Field label="Begründung"><input aria-label="Grund der Statusänderung" value={reason} onChange={event => setReason(event.target.value)} className={field} /></Field><p className="mt-3 text-[11px] leading-relaxed text-gray-500">Der Verlauf, gespeicherte Antworten, Fotos und Zeiten bleiben erhalten.</p><footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setStateAction(null)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || reason.trim().length < 3} onClick={() => void act(async () => { await requestSMDurcharbeitCampaign(`/${selected.id}/state`, { expectedRevision: selected.revision, status: stateAction, reason }, "PATCH"); setStateAction(null); reload(); })} className={primary}>Bestätigen</button></footer></CampaignDialog> : null}
    {periodEdit && selected ? <CampaignDialog error={error} title={`Fragebogen · ${monthName(month)}`} onClose={() => { if (!busy) setPeriodEdit(false); }}><div className="space-y-4"><Field label="Neue veröffentlichte Version"><AdminDropdown value={futureVersion} options={questionnaires} onChange={setFutureVersion} ariaLabel="Zukünftiger Fragebogen" placeholder="Fragebogen wählen" searchable /></Field><Field label="Begründung"><input value={reason} aria-label="Grund des Fragebogenwechsels" onChange={event => setReason(event.target.value)} className={field} /></Field></div><p className="mt-3 text-[10px] leading-relaxed text-gray-600">Der Wechsel ist nur möglich, solange in diesem zukünftigen Monat noch kein Besuch gestartet wurde.</p><footer className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={() => setPeriodEdit(false)} className={secondary}>Abbrechen</button><button type="button" disabled={busy || !futureVersion || reason.trim().length < 3} onClick={() => void act(async () => { const data = await requestSMDurcharbeitCampaign<{ periods: Array<{ id: string; month: string }> }>(`/${selected.id}/periods`); const period = data.periods.find(period => period.month === month); if (!period) throw new Error("Kalendermonat nicht gefunden."); await requestSMDurcharbeitCampaign(`/${selected.id}/periods/${period.id}/questionnaire`, { expectedRevision: selected.revision, questionnaireVersionId: futureVersion, reason }, "PATCH"); setPeriodEdit(false); reload(); })} className={primary}>Speichern</button></footer></CampaignDialog> : null}
  </main></SMDurcharbeitFilterTheme>;
}
